const express = require('express');
const router = express.Router();
const { getAllProducts } = require('../controller/productController');
const { registerStudent,updateStudent,updateStudentPartial,deleteStudent, StudentGetById } = require('../controller/studentController');
const { getAuthorWithBooks } = require('../controller/authorController');
const { login,register } = require('../controller/authController');
const { getUserProfile } = require('../controller/userController');
const verifyToken = require('../middleware/authMiddleware');

//router.post('/register', registerStudent);
router.put('/update/:id', updateStudent);
router.patch('/updatePartial/:id', updateStudentPartial);
router.delete('/delete/:id',deleteStudent);
router.get('/getById/:id',StudentGetById);
router.get('/products', getAllProducts);
router.get('/author/:id/books', getAuthorWithBooks);
router.post('/register', register);
router.post('/login', login);
router.get("/profile", verifyToken, getUserProfile);
module.exports = router;